//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMUser
    {
        public TMUser()
        {
            this.Comments = new HashSet<Comment>();
            this.TMTasks = new HashSet<TMTask>();
            this.TasksReports = new HashSet<TasksReport>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<TMTask> TMTasks { get; set; }
        public virtual ICollection<TasksReport> TasksReports { get; set; }
    }
}
